#服务器配置
server:
  port: 8888
  servlet:
    context-path: /houtai

spring:
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/laydb?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/static/
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info